/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarSponsorFundingRouteImport } from './../routes/_sidebar/sponsor-funding'
import { Route as SidebarRiskComplianceRouteImport } from './../routes/_sidebar/risk-compliance'
import { Route as SidebarProgramPortfolioRouteImport } from './../routes/_sidebar/program-portfolio'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarGovernmentRelationsRouteImport } from './../routes/_sidebar/government-relations'
import { Route as SidebarFinancialHealthRouteImport } from './../routes/_sidebar/financial-health'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarSponsorFundingRoute = SidebarSponsorFundingRouteImport.update({
  id: '/sponsor-funding',
  path: '/sponsor-funding',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRiskComplianceRoute = SidebarRiskComplianceRouteImport.update({
  id: '/risk-compliance',
  path: '/risk-compliance',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProgramPortfolioRoute = SidebarProgramPortfolioRouteImport.update({
  id: '/program-portfolio',
  path: '/program-portfolio',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarGovernmentRelationsRoute =
  SidebarGovernmentRelationsRouteImport.update({
    id: '/government-relations',
    path: '/government-relations',
    getParentRoute: () => SidebarRouteRoute,
  } as any)
const SidebarFinancialHealthRoute = SidebarFinancialHealthRouteImport.update({
  id: '/financial-health',
  path: '/financial-health',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/financial-health': typeof SidebarFinancialHealthRoute
  '/government-relations': typeof SidebarGovernmentRelationsRoute
  '/profile': typeof SidebarProfileRoute
  '/program-portfolio': typeof SidebarProgramPortfolioRoute
  '/risk-compliance': typeof SidebarRiskComplianceRoute
  '/sponsor-funding': typeof SidebarSponsorFundingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/financial-health': typeof SidebarFinancialHealthRoute
  '/government-relations': typeof SidebarGovernmentRelationsRoute
  '/profile': typeof SidebarProfileRoute
  '/program-portfolio': typeof SidebarProgramPortfolioRoute
  '/risk-compliance': typeof SidebarRiskComplianceRoute
  '/sponsor-funding': typeof SidebarSponsorFundingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/financial-health': typeof SidebarFinancialHealthRoute
  '/_sidebar/government-relations': typeof SidebarGovernmentRelationsRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/program-portfolio': typeof SidebarProgramPortfolioRoute
  '/_sidebar/risk-compliance': typeof SidebarRiskComplianceRoute
  '/_sidebar/sponsor-funding': typeof SidebarSponsorFundingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/financial-health'
    | '/government-relations'
    | '/profile'
    | '/program-portfolio'
    | '/risk-compliance'
    | '/sponsor-funding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/financial-health'
    | '/government-relations'
    | '/profile'
    | '/program-portfolio'
    | '/risk-compliance'
    | '/sponsor-funding'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/financial-health'
    | '/_sidebar/government-relations'
    | '/_sidebar/profile'
    | '/_sidebar/program-portfolio'
    | '/_sidebar/risk-compliance'
    | '/_sidebar/sponsor-funding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/sponsor-funding': {
      id: '/_sidebar/sponsor-funding'
      path: '/sponsor-funding'
      fullPath: '/sponsor-funding'
      preLoaderRoute: typeof SidebarSponsorFundingRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/risk-compliance': {
      id: '/_sidebar/risk-compliance'
      path: '/risk-compliance'
      fullPath: '/risk-compliance'
      preLoaderRoute: typeof SidebarRiskComplianceRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/program-portfolio': {
      id: '/_sidebar/program-portfolio'
      path: '/program-portfolio'
      fullPath: '/program-portfolio'
      preLoaderRoute: typeof SidebarProgramPortfolioRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/government-relations': {
      id: '/_sidebar/government-relations'
      path: '/government-relations'
      fullPath: '/government-relations'
      preLoaderRoute: typeof SidebarGovernmentRelationsRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/financial-health': {
      id: '/_sidebar/financial-health'
      path: '/financial-health'
      fullPath: '/financial-health'
      preLoaderRoute: typeof SidebarFinancialHealthRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarFinancialHealthRoute: typeof SidebarFinancialHealthRoute
  SidebarGovernmentRelationsRoute: typeof SidebarGovernmentRelationsRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarProgramPortfolioRoute: typeof SidebarProgramPortfolioRoute
  SidebarRiskComplianceRoute: typeof SidebarRiskComplianceRoute
  SidebarSponsorFundingRoute: typeof SidebarSponsorFundingRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarFinancialHealthRoute: SidebarFinancialHealthRoute,
  SidebarGovernmentRelationsRoute: SidebarGovernmentRelationsRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarProgramPortfolioRoute: SidebarProgramPortfolioRoute,
  SidebarRiskComplianceRoute: SidebarRiskComplianceRoute,
  SidebarSponsorFundingRoute: SidebarSponsorFundingRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
