command: ["uvicorn", "financial_command_center.backend.app:app", "--workers", "2"]

# Enable user impersonation to pass OBO tokens
permissions:
  - user_access_token

env:
  # Genie Space IDs for each schema
  - name: FINANCIAL_COMMAND_CENTER_GENIE_SPACE_FINANCIAL_HEALTH
    value: "01f0dec4f3971e7cac39a1c9e71eb1da"
  - name: FINANCIAL_COMMAND_CENTER_GENIE_SPACE_PROGRAM_PORTFOLIO
    value: "01f0dec4f3ea120184ddd4d23bf81627"
  - name: FINANCIAL_COMMAND_CENTER_GENIE_SPACE_SPONSOR_FUNDING
    value: "01f0dec4f43318128fed86372124f817"
  - name: FINANCIAL_COMMAND_CENTER_GENIE_SPACE_RISK_COMPLIANCE
    value: "01f0dec4f47c1df2968ca069d03aad24"
  - name: FINANCIAL_COMMAND_CENTER_GENIE_SPACE_GOVERNMENT_RELATIONS
    value: "01f0dec4f4c3162fa63ab11239ff4e1b"