/**
 * Static Sponsor Funding data
 * Realistic demo values for cost stewardship, efficiency, and sponsor health.
 * Will be replaced with Databricks SQL Warehouse queries in production.
 */

import type { SponsorFundingSnapshot } from "./types";

export const staticSponsorFundingSnapshot: SponsorFundingSnapshot = {
  asOfDate: "2024-12-15",
  timeWindow: "YTD",
  sponsors: [
    { id: "dod", name: "Department of Defense", agencyGroup: "Defense", abbreviation: "DoD" },
    { id: "dhs", name: "Department of Homeland Security", agencyGroup: "Homeland Security", abbreviation: "DHS" },
    { id: "hhs", name: "Department of Health & Human Services", agencyGroup: "Health & Human Services", abbreviation: "HHS" },
    { id: "doe", name: "Department of Energy", agencyGroup: "Energy", abbreviation: "DOE" },
    { id: "va", name: "Department of Veterans Affairs", agencyGroup: "Veterans Affairs", abbreviation: "VA" },
    { id: "doj", name: "Department of Justice", agencyGroup: "Justice", abbreviation: "DOJ" },
    { id: "faa", name: "Federal Aviation Administration", agencyGroup: "Transportation", abbreviation: "FAA" },
    { id: "irs", name: "Internal Revenue Service", agencyGroup: "Treasury", abbreviation: "IRS" },
  ],
  ffrdcs: [
    { id: "cems", shortName: "CEM", fullName: "Center for Enterprise Modernization" },
    { id: "cve", shortName: "CVE", fullName: "Center for Veterans Enterprise" },
    { id: "hssedi", shortName: "HSSEDI", fullName: "Homeland Security Systems Engineering & Development Institute" },
    { id: "jsac", shortName: "JEMC", fullName: "Judiciary Engineering and Modernization Center" },
    { id: "nsc", shortName: "NSEC", fullName: "National Security Engineering Center" },
    { id: "cms", shortName: "CAMH", fullName: "CMS Alliance to Modernize Healthcare" },
  ],
  stewardship: [
    {
      sponsorId: "dod",
      sponsorName: "Department of Defense",
      sponsorAbbreviation: "DoD",
      cpi: 1.04,
      actualSpend: 1235000000,
      estimatedSpend: 1285000000,
      overheadRatio: 18.2,
      overheadByFfrdc: [
        { ffrdcId: "nsc", ffrdcName: "NSEC", overheadRatio: 17.5, target: 20 },
        { ffrdcId: "cems", ffrdcName: "CEM", overheadRatio: 19.8, target: 20 },
        { ffrdcId: "hssedi", ffrdcName: "HSSEDI", overheadRatio: 18.1, target: 20 },
      ],
      indirectRateCurrent: 42.5,
      indirectRateCap: 45.0,
      indirectRateTrend: [
        { month: "Jul", actualRate: 41.2, negotiatedCap: 45.0 },
        { month: "Aug", actualRate: 41.8, negotiatedCap: 45.0 },
        { month: "Sep", actualRate: 42.1, negotiatedCap: 45.0 },
        { month: "Oct", actualRate: 42.3, negotiatedCap: 45.0 },
        { month: "Nov", actualRate: 42.4, negotiatedCap: 45.0 },
        { month: "Dec", actualRate: 42.5, negotiatedCap: 45.0 },
      ],
      billableUtilizationPct: 84.2,
      status: "excellent",
    },
    {
      sponsorId: "dhs",
      sponsorName: "Department of Homeland Security",
      sponsorAbbreviation: "DHS",
      cpi: 1.02,
      actualSpend: 436000000,
      estimatedSpend: 445000000,
      overheadRatio: 19.5,
      overheadByFfrdc: [
        { ffrdcId: "hssedi", ffrdcName: "HSSEDI", overheadRatio: 19.2, target: 20 },
        { ffrdcId: "cems", ffrdcName: "CEM", overheadRatio: 20.1, target: 20 },
      ],
      indirectRateCurrent: 43.8,
      indirectRateCap: 46.0,
      indirectRateTrend: [
        { month: "Jul", actualRate: 42.5, negotiatedCap: 46.0 },
        { month: "Aug", actualRate: 43.0, negotiatedCap: 46.0 },
        { month: "Sep", actualRate: 43.2, negotiatedCap: 46.0 },
        { month: "Oct", actualRate: 43.5, negotiatedCap: 46.0 },
        { month: "Nov", actualRate: 43.6, negotiatedCap: 46.0 },
        { month: "Dec", actualRate: 43.8, negotiatedCap: 46.0 },
      ],
      billableUtilizationPct: 81.5,
      status: "good",
    },
    {
      sponsorId: "hhs",
      sponsorName: "Department of Health & Human Services",
      sponsorAbbreviation: "HHS",
      cpi: 0.97,
      actualSpend: 330000000,
      estimatedSpend: 320000000,
      overheadRatio: 21.2,
      overheadByFfrdc: [
        { ffrdcId: "cms", ffrdcName: "CAMH", overheadRatio: 21.5, target: 20 },
        { ffrdcId: "cems", ffrdcName: "CEM", overheadRatio: 20.8, target: 20 },
      ],
      indirectRateCurrent: 44.2,
      indirectRateCap: 44.0,
      indirectRateTrend: [
        { month: "Jul", actualRate: 43.0, negotiatedCap: 44.0 },
        { month: "Aug", actualRate: 43.4, negotiatedCap: 44.0 },
        { month: "Sep", actualRate: 43.7, negotiatedCap: 44.0 },
        { month: "Oct", actualRate: 43.9, negotiatedCap: 44.0 },
        { month: "Nov", actualRate: 44.0, negotiatedCap: 44.0 },
        { month: "Dec", actualRate: 44.2, negotiatedCap: 44.0 },
      ],
      billableUtilizationPct: 78.3,
      status: "attention",
    },
    {
      sponsorId: "doe",
      sponsorName: "Department of Energy",
      sponsorAbbreviation: "DOE",
      cpi: 0.91,
      actualSpend: 214000000,
      estimatedSpend: 195000000,
      overheadRatio: 23.8,
      overheadByFfrdc: [
        { ffrdcId: "nsc", ffrdcName: "NSEC", overheadRatio: 23.5, target: 20 },
        { ffrdcId: "cems", ffrdcName: "CEM", overheadRatio: 24.2, target: 20 },
      ],
      indirectRateCurrent: 47.5,
      indirectRateCap: 45.0,
      indirectRateTrend: [
        { month: "Jul", actualRate: 44.8, negotiatedCap: 45.0 },
        { month: "Aug", actualRate: 45.5, negotiatedCap: 45.0 },
        { month: "Sep", actualRate: 46.2, negotiatedCap: 45.0 },
        { month: "Oct", actualRate: 46.8, negotiatedCap: 45.0 },
        { month: "Nov", actualRate: 47.2, negotiatedCap: 45.0 },
        { month: "Dec", actualRate: 47.5, negotiatedCap: 45.0 },
      ],
      billableUtilizationPct: 72.1,
      status: "critical",
    },
    {
      sponsorId: "va",
      sponsorName: "Department of Veterans Affairs",
      sponsorAbbreviation: "VA",
      cpi: 1.06,
      actualSpend: 198000000,
      estimatedSpend: 210000000,
      overheadRatio: 17.8,
      overheadByFfrdc: [
        { ffrdcId: "cve", ffrdcName: "CVE", overheadRatio: 17.2, target: 20 },
        { ffrdcId: "cms", ffrdcName: "CAMH", overheadRatio: 18.5, target: 20 },
      ],
      indirectRateCurrent: 41.2,
      indirectRateCap: 44.0,
      indirectRateTrend: [
        { month: "Jul", actualRate: 40.5, negotiatedCap: 44.0 },
        { month: "Aug", actualRate: 40.7, negotiatedCap: 44.0 },
        { month: "Sep", actualRate: 40.9, negotiatedCap: 44.0 },
        { month: "Oct", actualRate: 41.0, negotiatedCap: 44.0 },
        { month: "Nov", actualRate: 41.1, negotiatedCap: 44.0 },
        { month: "Dec", actualRate: 41.2, negotiatedCap: 44.0 },
      ],
      billableUtilizationPct: 85.8,
      status: "excellent",
    },
    {
      sponsorId: "doj",
      sponsorName: "Department of Justice",
      sponsorAbbreviation: "DOJ",
      cpi: 1.01,
      actualSpend: 140500000,
      estimatedSpend: 142000000,
      overheadRatio: 19.8,
      overheadByFfrdc: [
        { ffrdcId: "jsac", ffrdcName: "JEMC", overheadRatio: 19.5, target: 20 },
        { ffrdcId: "cems", ffrdcName: "CEM", overheadRatio: 20.2, target: 20 },
      ],
      indirectRateCurrent: 43.5,
      indirectRateCap: 45.0,
      indirectRateTrend: [
        { month: "Jul", actualRate: 42.8, negotiatedCap: 45.0 },
        { month: "Aug", actualRate: 43.0, negotiatedCap: 45.0 },
        { month: "Sep", actualRate: 43.1, negotiatedCap: 45.0 },
        { month: "Oct", actualRate: 43.3, negotiatedCap: 45.0 },
        { month: "Nov", actualRate: 43.4, negotiatedCap: 45.0 },
        { month: "Dec", actualRate: 43.5, negotiatedCap: 45.0 },
      ],
      billableUtilizationPct: 80.2,
      status: "good",
    },
    {
      sponsorId: "faa",
      sponsorName: "Federal Aviation Administration",
      sponsorAbbreviation: "FAA",
      cpi: 1.03,
      actualSpend: 160200000,
      estimatedSpend: 165000000,
      overheadRatio: 18.9,
      overheadByFfrdc: [
        { ffrdcId: "cems", ffrdcName: "CEM", overheadRatio: 18.5, target: 20 },
        { ffrdcId: "nsc", ffrdcName: "NSEC", overheadRatio: 19.3, target: 20 },
      ],
      indirectRateCurrent: 42.8,
      indirectRateCap: 45.0,
      indirectRateTrend: [
        { month: "Jul", actualRate: 41.5, negotiatedCap: 45.0 },
        { month: "Aug", actualRate: 41.9, negotiatedCap: 45.0 },
        { month: "Sep", actualRate: 42.2, negotiatedCap: 45.0 },
        { month: "Oct", actualRate: 42.5, negotiatedCap: 45.0 },
        { month: "Nov", actualRate: 42.7, negotiatedCap: 45.0 },
        { month: "Dec", actualRate: 42.8, negotiatedCap: 45.0 },
      ],
      billableUtilizationPct: 82.5,
      status: "good",
    },
    {
      sponsorId: "irs",
      sponsorName: "Internal Revenue Service",
      sponsorAbbreviation: "IRS",
      cpi: 0.94,
      actualSpend: 90400000,
      estimatedSpend: 85000000,
      overheadRatio: 22.5,
      overheadByFfrdc: [
        { ffrdcId: "cems", ffrdcName: "CEM", overheadRatio: 22.5, target: 20 },
      ],
      indirectRateCurrent: 46.2,
      indirectRateCap: 45.0,
      indirectRateTrend: [
        { month: "Jul", actualRate: 44.5, negotiatedCap: 45.0 },
        { month: "Aug", actualRate: 45.0, negotiatedCap: 45.0 },
        { month: "Sep", actualRate: 45.4, negotiatedCap: 45.0 },
        { month: "Oct", actualRate: 45.8, negotiatedCap: 45.0 },
        { month: "Nov", actualRate: 46.0, negotiatedCap: 45.0 },
        { month: "Dec", actualRate: 46.2, negotiatedCap: 45.0 },
      ],
      billableUtilizationPct: 74.8,
      status: "critical",
    },
  ],
  efficiency: [
    {
      ffrdcId: "nsc",
      ffrdcName: "NSEC",
      costPerTechFte: 142300,
      industryBenchmark: 155000,
      benchPct: 8.2,
      benchTrend: [
        { month: "Jul", benchPct: 7.5 },
        { month: "Aug", benchPct: 7.8 },
        { month: "Sep", benchPct: 8.0 },
        { month: "Oct", benchPct: 8.1 },
        { month: "Nov", benchPct: 8.0 },
        { month: "Dec", benchPct: 8.2 },
      ],
      headcountVsDemand: [
        { month: "Jul", headcount: 5750, demand: 5600 },
        { month: "Aug", headcount: 5780, demand: 5650 },
        { month: "Sep", headcount: 5800, demand: 5700 },
        { month: "Oct", headcount: 5810, demand: 5720 },
        { month: "Nov", headcount: 5815, demand: 5750 },
        { month: "Dec", headcount: 5820, demand: 5780 },
      ],
      currentHeadcount: 5820,
      currentDemand: 5780,
    },
    {
      ffrdcId: "cems",
      ffrdcName: "CEM",
      costPerTechFte: 166500,
      industryBenchmark: 155000,
      benchPct: 12.5,
      benchTrend: [
        { month: "Jul", benchPct: 10.2 },
        { month: "Aug", benchPct: 10.8 },
        { month: "Sep", benchPct: 11.5 },
        { month: "Oct", benchPct: 12.0 },
        { month: "Nov", benchPct: 12.3 },
        { month: "Dec", benchPct: 12.5 },
      ],
      headcountVsDemand: [
        { month: "Jul", headcount: 2400, demand: 2350 },
        { month: "Aug", headcount: 2420, demand: 2300 },
        { month: "Sep", headcount: 2440, demand: 2280 },
        { month: "Oct", headcount: 2445, demand: 2250 },
        { month: "Nov", headcount: 2448, demand: 2220 },
        { month: "Dec", headcount: 2450, demand: 2200 },
      ],
      currentHeadcount: 2450,
      currentDemand: 2200,
    },
    {
      ffrdcId: "hssedi",
      ffrdcName: "HSSEDI",
      costPerTechFte: 170700,
      industryBenchmark: 155000,
      benchPct: 9.8,
      benchTrend: [
        { month: "Jul", benchPct: 9.0 },
        { month: "Aug", benchPct: 9.2 },
        { month: "Sep", benchPct: 9.4 },
        { month: "Oct", benchPct: 9.5 },
        { month: "Nov", benchPct: 9.7 },
        { month: "Dec", benchPct: 9.8 },
      ],
      headcountVsDemand: [
        { month: "Jul", headcount: 1950, demand: 1900 },
        { month: "Aug", headcount: 1960, demand: 1920 },
        { month: "Sep", headcount: 1970, demand: 1940 },
        { month: "Oct", headcount: 1975, demand: 1950 },
        { month: "Nov", headcount: 1978, demand: 1960 },
        { month: "Dec", headcount: 1980, demand: 1970 },
      ],
      currentHeadcount: 1980,
      currentDemand: 1970,
    },
    {
      ffrdcId: "cve",
      ffrdcName: "CVE",
      costPerTechFte: 174400,
      industryBenchmark: 155000,
      benchPct: 6.5,
      benchTrend: [
        { month: "Jul", benchPct: 5.8 },
        { month: "Aug", benchPct: 6.0 },
        { month: "Sep", benchPct: 6.2 },
        { month: "Oct", benchPct: 6.3 },
        { month: "Nov", benchPct: 6.4 },
        { month: "Dec", benchPct: 6.5 },
      ],
      headcountVsDemand: [
        { month: "Jul", headcount: 810, demand: 800 },
        { month: "Aug", headcount: 812, demand: 805 },
        { month: "Sep", headcount: 815, demand: 810 },
        { month: "Oct", headcount: 817, demand: 812 },
        { month: "Nov", headcount: 818, demand: 815 },
        { month: "Dec", headcount: 820, demand: 818 },
      ],
      currentHeadcount: 820,
      currentDemand: 818,
    },
    {
      ffrdcId: "jsac",
      ffrdcName: "JEMC",
      costPerTechFte: 163800,
      industryBenchmark: 155000,
      benchPct: 7.2,
      benchTrend: [
        { month: "Jul", benchPct: 6.5 },
        { month: "Aug", benchPct: 6.7 },
        { month: "Sep", benchPct: 6.9 },
        { month: "Oct", benchPct: 7.0 },
        { month: "Nov", benchPct: 7.1 },
        { month: "Dec", benchPct: 7.2 },
      ],
      headcountVsDemand: [
        { month: "Jul", headcount: 570, demand: 560 },
        { month: "Aug", headcount: 574, demand: 565 },
        { month: "Sep", headcount: 576, demand: 568 },
        { month: "Oct", headcount: 578, demand: 570 },
        { month: "Nov", headcount: 579, demand: 572 },
        { month: "Dec", headcount: 580, demand: 575 },
      ],
      currentHeadcount: 580,
      currentDemand: 575,
    },
    {
      ffrdcId: "cms",
      ffrdcName: "CAMH",
      costPerTechFte: 165900,
      industryBenchmark: 155000,
      benchPct: 11.2,
      benchTrend: [
        { month: "Jul", benchPct: 9.5 },
        { month: "Aug", benchPct: 10.0 },
        { month: "Sep", benchPct: 10.4 },
        { month: "Oct", benchPct: 10.8 },
        { month: "Nov", benchPct: 11.0 },
        { month: "Dec", benchPct: 11.2 },
      ],
      headcountVsDemand: [
        { month: "Jul", headcount: 1320, demand: 1280 },
        { month: "Aug", headcount: 1330, demand: 1260 },
        { month: "Sep", headcount: 1340, demand: 1240 },
        { month: "Oct", headcount: 1345, demand: 1230 },
        { month: "Nov", headcount: 1348, demand: 1220 },
        { month: "Dec", headcount: 1350, demand: 1210 },
      ],
      currentHeadcount: 1350,
      currentDemand: 1210,
    },
  ],
  health: [
    {
      sponsorId: "dod",
      sponsorName: "Department of Defense",
      sponsorAbbreviation: "DoD",
      defectRate: 2.1,
      defectRateTrend: [
        { month: "Jul", value: 2.5 },
        { month: "Aug", value: 2.4 },
        { month: "Sep", value: 2.3 },
        { month: "Oct", value: 2.2 },
        { month: "Nov", value: 2.1 },
        { month: "Dec", value: 2.1 },
      ],
      reworkPct: 4.2,
      reworkPctTrend: [
        { month: "Jul", value: 4.8 },
        { month: "Aug", value: 4.6 },
        { month: "Sep", value: 4.5 },
        { month: "Oct", value: 4.4 },
        { month: "Nov", value: 4.3 },
        { month: "Dec", value: 4.2 },
      ],
      onTimeDeliveryPct: 94.5,
      onTimeDeliveryTrend: [
        { month: "Jul", value: 92.0 },
        { month: "Aug", value: 92.5 },
        { month: "Sep", value: 93.0 },
        { month: "Oct", value: 93.8 },
        { month: "Nov", value: 94.2 },
        { month: "Dec", value: 94.5 },
      ],
      budgetVariancePct: 4.0,
      budgetVarianceTrend: [
        { month: "Jul", value: 2.5 },
        { month: "Aug", value: 3.0 },
        { month: "Sep", value: 3.2 },
        { month: "Oct", value: 3.5 },
        { month: "Nov", value: 3.8 },
        { month: "Dec", value: 4.0 },
      ],
      npsScore: 72,
      npsTrend: [
        { month: "Jul", value: 68 },
        { month: "Aug", value: 69 },
        { month: "Sep", value: 70 },
        { month: "Oct", value: 71 },
        { month: "Nov", value: 71 },
        { month: "Dec", value: 72 },
      ],
      healthScore: 88,
      status: "healthy",
    },
    {
      sponsorId: "dhs",
      sponsorName: "Department of Homeland Security",
      sponsorAbbreviation: "DHS",
      defectRate: 2.8,
      defectRateTrend: [
        { month: "Jul", value: 3.0 },
        { month: "Aug", value: 2.9 },
        { month: "Sep", value: 2.9 },
        { month: "Oct", value: 2.8 },
        { month: "Nov", value: 2.8 },
        { month: "Dec", value: 2.8 },
      ],
      reworkPct: 5.5,
      reworkPctTrend: [
        { month: "Jul", value: 5.8 },
        { month: "Aug", value: 5.7 },
        { month: "Sep", value: 5.6 },
        { month: "Oct", value: 5.5 },
        { month: "Nov", value: 5.5 },
        { month: "Dec", value: 5.5 },
      ],
      onTimeDeliveryPct: 91.2,
      onTimeDeliveryTrend: [
        { month: "Jul", value: 89.5 },
        { month: "Aug", value: 90.0 },
        { month: "Sep", value: 90.5 },
        { month: "Oct", value: 90.8 },
        { month: "Nov", value: 91.0 },
        { month: "Dec", value: 91.2 },
      ],
      budgetVariancePct: 2.0,
      budgetVarianceTrend: [
        { month: "Jul", value: 1.5 },
        { month: "Aug", value: 1.6 },
        { month: "Sep", value: 1.7 },
        { month: "Oct", value: 1.8 },
        { month: "Nov", value: 1.9 },
        { month: "Dec", value: 2.0 },
      ],
      npsScore: 65,
      npsTrend: [
        { month: "Jul", value: 62 },
        { month: "Aug", value: 63 },
        { month: "Sep", value: 64 },
        { month: "Oct", value: 64 },
        { month: "Nov", value: 65 },
        { month: "Dec", value: 65 },
      ],
      healthScore: 78,
      status: "healthy",
    },
    {
      sponsorId: "hhs",
      sponsorName: "Department of Health & Human Services",
      sponsorAbbreviation: "HHS",
      defectRate: 3.5,
      defectRateTrend: [
        { month: "Jul", value: 3.2 },
        { month: "Aug", value: 3.3 },
        { month: "Sep", value: 3.4 },
        { month: "Oct", value: 3.4 },
        { month: "Nov", value: 3.5 },
        { month: "Dec", value: 3.5 },
      ],
      reworkPct: 7.2,
      reworkPctTrend: [
        { month: "Jul", value: 6.5 },
        { month: "Aug", value: 6.8 },
        { month: "Sep", value: 7.0 },
        { month: "Oct", value: 7.1 },
        { month: "Nov", value: 7.2 },
        { month: "Dec", value: 7.2 },
      ],
      onTimeDeliveryPct: 87.5,
      onTimeDeliveryTrend: [
        { month: "Jul", value: 88.5 },
        { month: "Aug", value: 88.2 },
        { month: "Sep", value: 88.0 },
        { month: "Oct", value: 87.8 },
        { month: "Nov", value: 87.6 },
        { month: "Dec", value: 87.5 },
      ],
      budgetVariancePct: -3.1,
      budgetVarianceTrend: [
        { month: "Jul", value: -1.5 },
        { month: "Aug", value: -2.0 },
        { month: "Sep", value: -2.3 },
        { month: "Oct", value: -2.6 },
        { month: "Nov", value: -2.9 },
        { month: "Dec", value: -3.1 },
      ],
      npsScore: 52,
      npsTrend: [
        { month: "Jul", value: 58 },
        { month: "Aug", value: 56 },
        { month: "Sep", value: 55 },
        { month: "Oct", value: 54 },
        { month: "Nov", value: 53 },
        { month: "Dec", value: 52 },
      ],
      healthScore: 62,
      status: "attention",
    },
    {
      sponsorId: "doe",
      sponsorName: "Department of Energy",
      sponsorAbbreviation: "DOE",
      defectRate: 4.8,
      defectRateTrend: [
        { month: "Jul", value: 3.8 },
        { month: "Aug", value: 4.0 },
        { month: "Sep", value: 4.2 },
        { month: "Oct", value: 4.5 },
        { month: "Nov", value: 4.7 },
        { month: "Dec", value: 4.8 },
      ],
      reworkPct: 9.5,
      reworkPctTrend: [
        { month: "Jul", value: 7.5 },
        { month: "Aug", value: 8.0 },
        { month: "Sep", value: 8.5 },
        { month: "Oct", value: 9.0 },
        { month: "Nov", value: 9.3 },
        { month: "Dec", value: 9.5 },
      ],
      onTimeDeliveryPct: 78.2,
      onTimeDeliveryTrend: [
        { month: "Jul", value: 82.0 },
        { month: "Aug", value: 81.0 },
        { month: "Sep", value: 80.5 },
        { month: "Oct", value: 79.5 },
        { month: "Nov", value: 78.8 },
        { month: "Dec", value: 78.2 },
      ],
      budgetVariancePct: -9.7,
      budgetVarianceTrend: [
        { month: "Jul", value: -5.0 },
        { month: "Aug", value: -6.2 },
        { month: "Sep", value: -7.1 },
        { month: "Oct", value: -8.0 },
        { month: "Nov", value: -9.0 },
        { month: "Dec", value: -9.7 },
      ],
      npsScore: 35,
      npsTrend: [
        { month: "Jul", value: 48 },
        { month: "Aug", value: 45 },
        { month: "Sep", value: 42 },
        { month: "Oct", value: 40 },
        { month: "Nov", value: 38 },
        { month: "Dec", value: 35 },
      ],
      healthScore: 42,
      status: "critical",
    },
    {
      sponsorId: "va",
      sponsorName: "Department of Veterans Affairs",
      sponsorAbbreviation: "VA",
      defectRate: 1.8,
      defectRateTrend: [
        { month: "Jul", value: 2.2 },
        { month: "Aug", value: 2.1 },
        { month: "Sep", value: 2.0 },
        { month: "Oct", value: 1.9 },
        { month: "Nov", value: 1.9 },
        { month: "Dec", value: 1.8 },
      ],
      reworkPct: 3.8,
      reworkPctTrend: [
        { month: "Jul", value: 4.2 },
        { month: "Aug", value: 4.1 },
        { month: "Sep", value: 4.0 },
        { month: "Oct", value: 3.9 },
        { month: "Nov", value: 3.9 },
        { month: "Dec", value: 3.8 },
      ],
      onTimeDeliveryPct: 96.2,
      onTimeDeliveryTrend: [
        { month: "Jul", value: 94.5 },
        { month: "Aug", value: 95.0 },
        { month: "Sep", value: 95.5 },
        { month: "Oct", value: 95.8 },
        { month: "Nov", value: 96.0 },
        { month: "Dec", value: 96.2 },
      ],
      budgetVariancePct: 5.7,
      budgetVarianceTrend: [
        { month: "Jul", value: 4.0 },
        { month: "Aug", value: 4.5 },
        { month: "Sep", value: 5.0 },
        { month: "Oct", value: 5.3 },
        { month: "Nov", value: 5.5 },
        { month: "Dec", value: 5.7 },
      ],
      npsScore: 78,
      npsTrend: [
        { month: "Jul", value: 74 },
        { month: "Aug", value: 75 },
        { month: "Sep", value: 76 },
        { month: "Oct", value: 77 },
        { month: "Nov", value: 78 },
        { month: "Dec", value: 78 },
      ],
      healthScore: 92,
      status: "healthy",
    },
    {
      sponsorId: "doj",
      sponsorName: "Department of Justice",
      sponsorAbbreviation: "DOJ",
      defectRate: 2.5,
      defectRateTrend: [
        { month: "Jul", value: 2.6 },
        { month: "Aug", value: 2.6 },
        { month: "Sep", value: 2.5 },
        { month: "Oct", value: 2.5 },
        { month: "Nov", value: 2.5 },
        { month: "Dec", value: 2.5 },
      ],
      reworkPct: 5.0,
      reworkPctTrend: [
        { month: "Jul", value: 5.2 },
        { month: "Aug", value: 5.1 },
        { month: "Sep", value: 5.1 },
        { month: "Oct", value: 5.0 },
        { month: "Nov", value: 5.0 },
        { month: "Dec", value: 5.0 },
      ],
      onTimeDeliveryPct: 90.5,
      onTimeDeliveryTrend: [
        { month: "Jul", value: 89.0 },
        { month: "Aug", value: 89.5 },
        { month: "Sep", value: 90.0 },
        { month: "Oct", value: 90.2 },
        { month: "Nov", value: 90.4 },
        { month: "Dec", value: 90.5 },
      ],
      budgetVariancePct: 1.1,
      budgetVarianceTrend: [
        { month: "Jul", value: 0.5 },
        { month: "Aug", value: 0.7 },
        { month: "Sep", value: 0.8 },
        { month: "Oct", value: 0.9 },
        { month: "Nov", value: 1.0 },
        { month: "Dec", value: 1.1 },
      ],
      npsScore: 61,
      npsTrend: [
        { month: "Jul", value: 58 },
        { month: "Aug", value: 59 },
        { month: "Sep", value: 60 },
        { month: "Oct", value: 60 },
        { month: "Nov", value: 61 },
        { month: "Dec", value: 61 },
      ],
      healthScore: 75,
      status: "healthy",
    },
    {
      sponsorId: "faa",
      sponsorName: "Federal Aviation Administration",
      sponsorAbbreviation: "FAA",
      defectRate: 2.3,
      defectRateTrend: [
        { month: "Jul", value: 2.5 },
        { month: "Aug", value: 2.4 },
        { month: "Sep", value: 2.4 },
        { month: "Oct", value: 2.3 },
        { month: "Nov", value: 2.3 },
        { month: "Dec", value: 2.3 },
      ],
      reworkPct: 4.5,
      reworkPctTrend: [
        { month: "Jul", value: 4.8 },
        { month: "Aug", value: 4.7 },
        { month: "Sep", value: 4.6 },
        { month: "Oct", value: 4.5 },
        { month: "Nov", value: 4.5 },
        { month: "Dec", value: 4.5 },
      ],
      onTimeDeliveryPct: 93.0,
      onTimeDeliveryTrend: [
        { month: "Jul", value: 91.5 },
        { month: "Aug", value: 92.0 },
        { month: "Sep", value: 92.3 },
        { month: "Oct", value: 92.6 },
        { month: "Nov", value: 92.8 },
        { month: "Dec", value: 93.0 },
      ],
      budgetVariancePct: 2.9,
      budgetVarianceTrend: [
        { month: "Jul", value: 2.0 },
        { month: "Aug", value: 2.2 },
        { month: "Sep", value: 2.4 },
        { month: "Oct", value: 2.6 },
        { month: "Nov", value: 2.8 },
        { month: "Dec", value: 2.9 },
      ],
      npsScore: 68,
      npsTrend: [
        { month: "Jul", value: 65 },
        { month: "Aug", value: 66 },
        { month: "Sep", value: 67 },
        { month: "Oct", value: 67 },
        { month: "Nov", value: 68 },
        { month: "Dec", value: 68 },
      ],
      healthScore: 82,
      status: "healthy",
    },
    {
      sponsorId: "irs",
      sponsorName: "Internal Revenue Service",
      sponsorAbbreviation: "IRS",
      defectRate: 4.2,
      defectRateTrend: [
        { month: "Jul", value: 3.5 },
        { month: "Aug", value: 3.7 },
        { month: "Sep", value: 3.9 },
        { month: "Oct", value: 4.0 },
        { month: "Nov", value: 4.1 },
        { month: "Dec", value: 4.2 },
      ],
      reworkPct: 8.5,
      reworkPctTrend: [
        { month: "Jul", value: 7.0 },
        { month: "Aug", value: 7.5 },
        { month: "Sep", value: 7.8 },
        { month: "Oct", value: 8.1 },
        { month: "Nov", value: 8.3 },
        { month: "Dec", value: 8.5 },
      ],
      onTimeDeliveryPct: 82.0,
      onTimeDeliveryTrend: [
        { month: "Jul", value: 85.0 },
        { month: "Aug", value: 84.2 },
        { month: "Sep", value: 83.5 },
        { month: "Oct", value: 82.8 },
        { month: "Nov", value: 82.4 },
        { month: "Dec", value: 82.0 },
      ],
      budgetVariancePct: -6.4,
      budgetVarianceTrend: [
        { month: "Jul", value: -3.0 },
        { month: "Aug", value: -3.8 },
        { month: "Sep", value: -4.5 },
        { month: "Oct", value: -5.2 },
        { month: "Nov", value: -5.8 },
        { month: "Dec", value: -6.4 },
      ],
      npsScore: 42,
      npsTrend: [
        { month: "Jul", value: 52 },
        { month: "Aug", value: 50 },
        { month: "Sep", value: 48 },
        { month: "Oct", value: 46 },
        { month: "Nov", value: 44 },
        { month: "Dec", value: 42 },
      ],
      healthScore: 48,
      status: "critical",
    },
  ],
  renewals: [
    {
      sponsorId: "irs",
      sponsorName: "Internal Revenue Service",
      sponsorAbbreviation: "IRS",
      renewalDate: "2025-04-15",
      contractValue: 170000000,
      annualRunRate: 85000000,
      npsScore: 42,
      healthStatus: "critical",
      riskNotes: "NPS declining, budget overruns, schedule slippage. Urgent executive engagement needed.",
      daysUntilRenewal: 121,
    },
    {
      sponsorId: "doe",
      sponsorName: "Department of Energy",
      sponsorAbbreviation: "DOE",
      renewalDate: "2025-06-30",
      contractValue: 390000000,
      annualRunRate: 195000000,
      npsScore: 35,
      healthStatus: "critical",
      riskNotes: "Significant cost overruns and quality issues. Renewal at risk without immediate remediation.",
      daysUntilRenewal: 197,
    },
    {
      sponsorId: "hhs",
      sponsorName: "Department of Health & Human Services",
      sponsorAbbreviation: "HHS",
      renewalDate: "2025-09-30",
      contractValue: 640000000,
      annualRunRate: 320000000,
      npsScore: 52,
      healthStatus: "attention",
      riskNotes: "Budget variance trending negative. Proactive sponsor engagement recommended.",
      daysUntilRenewal: 289,
    },
    {
      sponsorId: "doj",
      sponsorName: "Department of Justice",
      sponsorAbbreviation: "DOJ",
      renewalDate: "2025-12-31",
      contractValue: 284000000,
      annualRunRate: 142000000,
      npsScore: 61,
      healthStatus: "healthy",
      riskNotes: "On track. Continue current engagement cadence.",
      daysUntilRenewal: 381,
    },
    {
      sponsorId: "dhs",
      sponsorName: "Department of Homeland Security",
      sponsorAbbreviation: "DHS",
      renewalDate: "2026-03-31",
      contractValue: 890000000,
      annualRunRate: 445000000,
      npsScore: 65,
      healthStatus: "healthy",
      riskNotes: "Strong relationship. Consider scope expansion discussions.",
      daysUntilRenewal: 471,
    },
    {
      sponsorId: "faa",
      sponsorName: "Federal Aviation Administration",
      sponsorAbbreviation: "FAA",
      renewalDate: "2026-06-30",
      contractValue: 495000000,
      annualRunRate: 165000000,
      npsScore: 68,
      healthStatus: "healthy",
      riskNotes: "Positive trajectory. Good candidate for multi-year extension.",
      daysUntilRenewal: 562,
    },
    {
      sponsorId: "dod",
      sponsorName: "Department of Defense",
      sponsorAbbreviation: "DoD",
      renewalDate: "2026-09-30",
      contractValue: 3855000000,
      annualRunRate: 1285000000,
      npsScore: 72,
      healthStatus: "healthy",
      riskNotes: "Flagship relationship. Excellent stewardship metrics.",
      daysUntilRenewal: 654,
    },
    {
      sponsorId: "va",
      sponsorName: "Department of Veterans Affairs",
      sponsorAbbreviation: "VA",
      renewalDate: "2027-03-31",
      contractValue: 630000000,
      annualRunRate: 210000000,
      npsScore: 78,
      healthStatus: "healthy",
      riskNotes: "Best-in-class performance. Model for other sponsor relationships.",
      daysUntilRenewal: 836,
    },
  ],
  summaryKpis: {
    avgCpi: 1.01,
    avgOverheadRatio: 20.2,
    avgBillableUtilization: 79.9,
    avgNps: 59.1,
    sponsorsAtRisk: 2,
    upcomingRenewals30Days: 0,
    upcomingRenewals90Days: 0,
  },
};

