/**
 * Static demo data for Government Relations & Strategic Positioning
 * This will be replaced with Databricks SQL Warehouse-backed APIs.
 */

import type {
  GovernmentRelationsSnapshot,
  MissionAreaRef,
  CompetitorRef,
  MissionAreaMarketShare,
  WinLossRecord,
  WinLossByMissionArea,
  CapabilityGap,
  PipelineItem,
  GovernmentInitiative,
} from "./types";

const missionAreas: MissionAreaRef[] = [
  { id: "defense", name: "Defense", description: "Department of Defense programs and initiatives" },
  { id: "cyber", name: "Cybersecurity", description: "Cybersecurity and critical infrastructure protection" },
  { id: "health", name: "Health", description: "Healthcare systems and public health initiatives" },
  { id: "aviation", name: "Aviation", description: "Aviation safety, air traffic, and aerospace" },
  { id: "climate", name: "Climate", description: "Climate science, sustainability, and environmental programs" },
  { id: "homeland", name: "Homeland Security", description: "DHS and domestic security programs" },
  { id: "intel", name: "Intelligence", description: "Intelligence community programs and analysis" },
];

const competitors: CompetitorRef[] = [
  { id: "lincoln", name: "MIT Lincoln Laboratory", abbreviation: "Lincoln Labs", type: "FFRDC" },
  { id: "rand", name: "RAND Corporation", abbreviation: "RAND", type: "FFRDC" },
  { id: "aerospace", name: "The Aerospace Corporation", abbreviation: "Aerospace", type: "FFRDC" },
  { id: "ida", name: "Institute for Defense Analyses", abbreviation: "IDA", type: "FFRDC" },
  { id: "cna", name: "CNA Corporation", abbreviation: "CNA", type: "FFRDC" },
  { id: "jhuapl", name: "Johns Hopkins APL", abbreviation: "JHU APL", type: "UARC" },
  { id: "sandia", name: "Sandia National Laboratories", abbreviation: "Sandia", type: "FFRDC" },
];

const marketShare: MissionAreaMarketShare[] = [
  {
    missionAreaId: "defense",
    missionAreaName: "Defense",
    totalAvailableMarket: 4_800_000_000,
    mitreShare: 18.5,
    mitreRevenue: 888_000_000,
    growthTrajectory: 3.2,
    mitreGrowthTrajectory: 4.1,
    competitorShares: [
      { competitorId: "lincoln", competitorName: "MIT Lincoln Laboratory", competitorAbbreviation: "Lincoln Labs", share: 22.3 },
      { competitorId: "aerospace", competitorName: "The Aerospace Corporation", competitorAbbreviation: "Aerospace", share: 15.8 },
      { competitorId: "ida", competitorName: "Institute for Defense Analyses", competitorAbbreviation: "IDA", share: 12.4 },
      { competitorId: "jhuapl", competitorName: "Johns Hopkins APL", competitorAbbreviation: "JHU APL", share: 14.2 },
    ],
  },
  {
    missionAreaId: "cyber",
    missionAreaName: "Cybersecurity",
    totalAvailableMarket: 2_100_000_000,
    mitreShare: 28.4,
    mitreRevenue: 596_400_000,
    growthTrajectory: 8.7,
    mitreGrowthTrajectory: 12.3,
    competitorShares: [
      { competitorId: "lincoln", competitorName: "MIT Lincoln Laboratory", competitorAbbreviation: "Lincoln Labs", share: 18.2 },
      { competitorId: "sandia", competitorName: "Sandia National Laboratories", competitorAbbreviation: "Sandia", share: 14.6 },
      { competitorId: "ida", competitorName: "Institute for Defense Analyses", competitorAbbreviation: "IDA", share: 8.3 },
    ],
  },
  {
    missionAreaId: "health",
    missionAreaName: "Health",
    totalAvailableMarket: 1_400_000_000,
    mitreShare: 32.1,
    mitreRevenue: 449_400_000,
    growthTrajectory: 5.4,
    mitreGrowthTrajectory: 6.8,
    competitorShares: [
      { competitorId: "rand", competitorName: "RAND Corporation", competitorAbbreviation: "RAND", share: 24.5 },
      { competitorId: "cna", competitorName: "CNA Corporation", competitorAbbreviation: "CNA", share: 11.2 },
    ],
  },
  {
    missionAreaId: "aviation",
    missionAreaName: "Aviation",
    totalAvailableMarket: 1_200_000_000,
    mitreShare: 45.2,
    mitreRevenue: 542_400_000,
    growthTrajectory: 2.1,
    mitreGrowthTrajectory: 1.8,
    competitorShares: [
      { competitorId: "aerospace", competitorName: "The Aerospace Corporation", competitorAbbreviation: "Aerospace", share: 18.7 },
      { competitorId: "lincoln", competitorName: "MIT Lincoln Laboratory", competitorAbbreviation: "Lincoln Labs", share: 8.4 },
    ],
  },
  {
    missionAreaId: "climate",
    missionAreaName: "Climate",
    totalAvailableMarket: 680_000_000,
    mitreShare: 15.3,
    mitreRevenue: 104_040_000,
    growthTrajectory: 14.2,
    mitreGrowthTrajectory: 22.5,
    competitorShares: [
      { competitorId: "rand", competitorName: "RAND Corporation", competitorAbbreviation: "RAND", share: 28.4 },
      { competitorId: "sandia", competitorName: "Sandia National Laboratories", competitorAbbreviation: "Sandia", share: 19.8 },
    ],
  },
  {
    missionAreaId: "homeland",
    missionAreaName: "Homeland Security",
    totalAvailableMarket: 980_000_000,
    mitreShare: 38.6,
    mitreRevenue: 378_280_000,
    growthTrajectory: 4.5,
    mitreGrowthTrajectory: 5.2,
    competitorShares: [
      { competitorId: "rand", competitorName: "RAND Corporation", competitorAbbreviation: "RAND", share: 15.3 },
      { competitorId: "cna", competitorName: "CNA Corporation", competitorAbbreviation: "CNA", share: 12.8 },
      { competitorId: "ida", competitorName: "Institute for Defense Analyses", competitorAbbreviation: "IDA", share: 9.4 },
    ],
  },
  {
    missionAreaId: "intel",
    missionAreaName: "Intelligence",
    totalAvailableMarket: 1_850_000_000,
    mitreShare: 21.7,
    mitreRevenue: 401_450_000,
    growthTrajectory: 6.3,
    mitreGrowthTrajectory: 7.9,
    competitorShares: [
      { competitorId: "lincoln", competitorName: "MIT Lincoln Laboratory", competitorAbbreviation: "Lincoln Labs", share: 26.8 },
      { competitorId: "ida", competitorName: "Institute for Defense Analyses", competitorAbbreviation: "IDA", share: 18.2 },
      { competitorId: "sandia", competitorName: "Sandia National Laboratories", competitorAbbreviation: "Sandia", share: 12.5 },
    ],
  },
];

const winLossRecords: WinLossRecord[] = [
  { competitorId: "lincoln", competitorName: "MIT Lincoln Laboratory", competitorAbbreviation: "Lincoln Labs", wins: 12, losses: 18, netWins: -6, winRate: 40.0, totalOpportunities: 30, recentTrend: "improving" },
  { competitorId: "rand", competitorName: "RAND Corporation", competitorAbbreviation: "RAND", wins: 22, losses: 8, netWins: 14, winRate: 73.3, totalOpportunities: 30, recentTrend: "stable" },
  { competitorId: "aerospace", competitorName: "The Aerospace Corporation", competitorAbbreviation: "Aerospace", wins: 14, losses: 11, netWins: 3, winRate: 56.0, totalOpportunities: 25, recentTrend: "stable" },
  { competitorId: "ida", competitorName: "Institute for Defense Analyses", competitorAbbreviation: "IDA", wins: 18, losses: 12, netWins: 6, winRate: 60.0, totalOpportunities: 30, recentTrend: "improving" },
  { competitorId: "cna", competitorName: "CNA Corporation", competitorAbbreviation: "CNA", wins: 16, losses: 4, netWins: 12, winRate: 80.0, totalOpportunities: 20, recentTrend: "stable" },
  { competitorId: "jhuapl", competitorName: "Johns Hopkins APL", competitorAbbreviation: "JHU APL", wins: 8, losses: 14, netWins: -6, winRate: 36.4, totalOpportunities: 22, recentTrend: "declining" },
  { competitorId: "sandia", competitorName: "Sandia National Laboratories", competitorAbbreviation: "Sandia", wins: 11, losses: 9, netWins: 2, winRate: 55.0, totalOpportunities: 20, recentTrend: "improving" },
];

const winLossByMissionArea: WinLossByMissionArea[] = [
  { missionAreaId: "defense", missionAreaName: "Defense", wins: 24, losses: 31, winRate: 43.6 },
  { missionAreaId: "cyber", missionAreaName: "Cybersecurity", wins: 28, losses: 12, winRate: 70.0 },
  { missionAreaId: "health", missionAreaName: "Health", wins: 18, losses: 6, winRate: 75.0 },
  { missionAreaId: "aviation", missionAreaName: "Aviation", wins: 15, losses: 5, winRate: 75.0 },
  { missionAreaId: "climate", missionAreaName: "Climate", wins: 8, losses: 4, winRate: 66.7 },
  { missionAreaId: "homeland", missionAreaName: "Homeland Security", wins: 14, losses: 8, winRate: 63.6 },
  { missionAreaId: "intel", missionAreaName: "Intelligence", wins: 19, losses: 22, winRate: 46.3 },
];

const capabilityGaps: CapabilityGap[] = [
  {
    id: "gap-1",
    capability: "Quantum Computing Security",
    description: "Post-quantum cryptography and quantum-resistant security protocols",
    missionAreas: ["Cybersecurity", "Defense", "Intelligence"],
    severity: "critical",
    status: "addressing",
    sponsorDemand: 8,
    estimatedImpact: 145_000_000,
    identifiedDate: "2024-03-15",
    targetResolutionDate: "2025-06-30",
  },
  {
    id: "gap-2",
    capability: "AI/ML Safety & Assurance",
    description: "Testing and evaluation frameworks for AI system safety and reliability",
    missionAreas: ["Defense", "Aviation", "Health"],
    severity: "critical",
    status: "addressing",
    sponsorDemand: 12,
    estimatedImpact: 220_000_000,
    identifiedDate: "2024-01-10",
    targetResolutionDate: "2025-03-31",
  },
  {
    id: "gap-3",
    capability: "Space Domain Awareness",
    description: "Satellite tracking, space debris monitoring, and orbital analysis",
    missionAreas: ["Defense", "Intelligence"],
    severity: "high",
    status: "identified",
    sponsorDemand: 5,
    estimatedImpact: 85_000_000,
    identifiedDate: "2024-06-20",
  },
  {
    id: "gap-4",
    capability: "Climate Modeling Integration",
    description: "Integration of climate models with infrastructure resilience planning",
    missionAreas: ["Climate", "Homeland Security"],
    severity: "medium",
    status: "identified",
    sponsorDemand: 4,
    estimatedImpact: 52_000_000,
    identifiedDate: "2024-08-05",
  },
  {
    id: "gap-5",
    capability: "5G/6G Network Security",
    description: "Security architecture for next-generation wireless networks",
    missionAreas: ["Cybersecurity", "Defense", "Homeland Security"],
    severity: "high",
    status: "addressing",
    sponsorDemand: 7,
    estimatedImpact: 118_000_000,
    identifiedDate: "2024-02-28",
    targetResolutionDate: "2025-09-30",
  },
  {
    id: "gap-6",
    capability: "Biodefense Analytics",
    description: "Advanced analytics for biological threat detection and response",
    missionAreas: ["Health", "Homeland Security", "Defense"],
    severity: "medium",
    status: "identified",
    sponsorDemand: 3,
    estimatedImpact: 38_000_000,
    identifiedDate: "2024-09-12",
  },
];

const pipeline: PipelineItem[] = [
  {
    id: "pipe-1",
    name: "QuantumShield Technologies",
    type: "Acquisition",
    description: "Post-quantum cryptography solutions provider with proven algorithms",
    capabilityGapAddressed: "Quantum Computing Security",
    missionAreas: ["Cybersecurity", "Defense", "Intelligence"],
    stage: "Due Diligence",
    confidenceLevel: "high",
    estimatedImpact: 95_000_000,
    strategicValue: 9,
    estimatedCost: 42_000_000,
    complexity: 6,
    expectedCloseDate: "2025-04-15",
    leadOwner: "M. Chen",
    lastUpdated: "2024-12-10",
    notes: "Strong IP portfolio, team willing to relocate to McLean",
  },
  {
    id: "pipe-2",
    name: "SafeAI Labs",
    type: "Partnership",
    description: "AI safety research lab with expertise in formal verification",
    capabilityGapAddressed: "AI/ML Safety & Assurance",
    missionAreas: ["Defense", "Aviation", "Health"],
    stage: "Negotiation",
    confidenceLevel: "high",
    estimatedImpact: 78_000_000,
    strategicValue: 8,
    estimatedCost: 8_500_000,
    complexity: 4,
    expectedCloseDate: "2025-02-28",
    leadOwner: "J. Rodriguez",
    lastUpdated: "2024-12-15",
    notes: "MOU drafted, pending legal review",
  },
  {
    id: "pipe-3",
    name: "OrbitWatch Systems",
    type: "Acquisition",
    description: "Space situational awareness and tracking technology provider",
    capabilityGapAddressed: "Space Domain Awareness",
    missionAreas: ["Defense", "Intelligence"],
    stage: "Screening",
    confidenceLevel: "medium",
    estimatedImpact: 65_000_000,
    strategicValue: 7,
    estimatedCost: 28_000_000,
    complexity: 7,
    leadOwner: "A. Patel",
    lastUpdated: "2024-12-08",
  },
  {
    id: "pipe-4",
    name: "SecureWave Communications",
    type: "Partnership",
    description: "5G/6G security testing and certification services",
    capabilityGapAddressed: "5G/6G Network Security",
    missionAreas: ["Cybersecurity", "Defense", "Homeland Security"],
    stage: "Sourcing",
    confidenceLevel: "low",
    estimatedImpact: 42_000_000,
    strategicValue: 6,
    estimatedCost: 5_200_000,
    complexity: 5,
    leadOwner: "S. Kim",
    lastUpdated: "2024-12-01",
  },
  {
    id: "pipe-5",
    name: "ClimateResilience Analytics",
    type: "Investment",
    description: "Climate modeling and infrastructure vulnerability assessment",
    capabilityGapAddressed: "Climate Modeling Integration",
    missionAreas: ["Climate", "Homeland Security"],
    stage: "Screening",
    confidenceLevel: "medium",
    estimatedImpact: 35_000_000,
    strategicValue: 5,
    estimatedCost: 12_000_000,
    complexity: 4,
    leadOwner: "L. Thompson",
    lastUpdated: "2024-12-05",
  },
  {
    id: "pipe-6",
    name: "BioShield Dynamics",
    type: "Partnership",
    description: "Biodefense threat detection and early warning systems",
    capabilityGapAddressed: "Biodefense Analytics",
    missionAreas: ["Health", "Homeland Security", "Defense"],
    stage: "Due Diligence",
    confidenceLevel: "medium",
    estimatedImpact: 28_000_000,
    strategicValue: 6,
    estimatedCost: 4_800_000,
    complexity: 5,
    expectedCloseDate: "2025-06-30",
    leadOwner: "R. Martinez",
    lastUpdated: "2024-12-12",
  },
  {
    id: "pipe-7",
    name: "NexGen Cyber Defense",
    type: "Acquisition",
    description: "Zero-trust architecture and identity management solutions",
    capabilityGapAddressed: "5G/6G Network Security",
    missionAreas: ["Cybersecurity", "Defense"],
    stage: "Closed",
    confidenceLevel: "high",
    estimatedImpact: 52_000_000,
    strategicValue: 7,
    estimatedCost: 18_500_000,
    complexity: 5,
    expectedCloseDate: "2024-11-30",
    leadOwner: "M. Chen",
    lastUpdated: "2024-11-30",
    notes: "Successfully closed. Integration in progress.",
  },
];

const initiatives: GovernmentInitiative[] = [
  {
    id: "init-1",
    title: "National AI Strategy Update",
    type: "Executive Order",
    description: "New executive order mandating AI safety testing for federal systems",
    affectedSponsors: ["DoD", "DHS", "FAA", "HHS"],
    affectedMissionAreas: ["Defense", "Aviation", "Health", "Homeland Security"],
    budgetImpact: 450_000_000,
    impact: "positive",
    effectiveDate: "2025-03-01",
    source: "White House",
    dateIdentified: "2024-10-15",
  },
  {
    id: "init-2",
    title: "Cybersecurity Modernization Act",
    type: "Legislation",
    description: "Congressional bill to fund federal cybersecurity infrastructure upgrades",
    affectedSponsors: ["CISA", "DoD", "NSA"],
    affectedMissionAreas: ["Cybersecurity", "Defense", "Intelligence"],
    budgetImpact: 820_000_000,
    impact: "positive",
    effectiveDate: "2025-10-01",
    source: "Congress",
    dateIdentified: "2024-09-20",
  },
  {
    id: "init-3",
    title: "Climate Resilience Infrastructure Program",
    type: "Budget Request",
    description: "FY26 budget request for climate adaptation and infrastructure hardening",
    affectedSponsors: ["EPA", "DHS", "DoE"],
    affectedMissionAreas: ["Climate", "Homeland Security"],
    budgetImpact: 180_000_000,
    impact: "positive",
    source: "OMB",
    dateIdentified: "2024-11-05",
  },
  {
    id: "init-4",
    title: "Defense Budget Sequestration Risk",
    type: "Policy Change",
    description: "Potential across-the-board defense spending cuts if debt ceiling negotiations fail",
    affectedSponsors: ["DoD"],
    affectedMissionAreas: ["Defense"],
    budgetImpact: -350_000_000,
    impact: "negative",
    source: "Congressional Budget Office",
    dateIdentified: "2024-12-01",
  },
];

// Calculate summary KPIs
const totalTAM = marketShare.reduce((sum, m) => sum + m.totalAvailableMarket, 0);
const totalMitreRevenue = marketShare.reduce((sum, m) => sum + m.mitreRevenue, 0);
const overallMarketShare = (totalMitreRevenue / totalTAM) * 100;

const totalWins = winLossRecords.reduce((sum, r) => sum + r.wins, 0);
const totalLosses = winLossRecords.reduce((sum, r) => sum + r.losses, 0);
const overallWinRate = (totalWins / (totalWins + totalLosses)) * 100;

const activePipeline = pipeline.filter((p) => p.stage !== "Closed");
const activePipelineValue = activePipeline.reduce((sum, p) => sum + p.estimatedImpact, 0);

const criticalGaps = capabilityGaps.filter((g) => g.severity === "critical");
const upcomingInitiatives = initiatives.filter((i) => i.impact === "positive");

export const staticGovernmentRelationsSnapshot: GovernmentRelationsSnapshot = {
  asOfDate: new Date().toISOString().split("T")[0],
  timeWindow: "YTD",
  fiscalYear: "FY25",

  missionAreas,
  competitors,

  marketShare,
  winLossRecords,
  winLossByMissionArea,
  capabilityGaps,

  pipeline,
  initiatives,

  summaryKpis: {
    overallMarketShare: Math.round(overallMarketShare * 10) / 10,
    marketShareTrend: 2.8,
    totalAddressableMarket: totalTAM,
    mitreRevenue: totalMitreRevenue,
    overallWinRate: Math.round(overallWinRate * 10) / 10,
    winRateTrend: 4.2,
    activePipelineValue,
    pipelineItemsCount: activePipeline.length,
    criticalGapsCount: criticalGaps.length,
    upcomingInitiativesCount: upcomingInitiatives.length,
  },
};

